### ISSUE TITLE
Why use AJAX for Dependent Fields ?

### ISSUE THREAD

**Issue by metalenger** [vafour/vafpress-framework#19]
I wanted to know if there was any particular reason that you guys used AJAX for Dependent Fields?

Why not just load them at first and then use hide/show? Because clearly using AJAX for this purpose only increase the waiting time before saving and this becomes more clear if you test it on a slow internet connection/hosting service.

**Comment by ayublin** [comment]
Hi Metalenger,

That's because we want to give the developers full controls on how the dependency will works, so it's not just simple show and hide based on a toggle, but developers can use their own function in their PHP code with any kind of logic that will determine the rule of the dependency. This enables developers to have complex dependency relation, using multiple controls and any types of controls.

**Comment by metalenger** [comment]
Thanks for the clarification ;)
