### ISSUE TITLE
Use only Theme Options / Metaboxes part

### ISSUE THREAD

**Issue by Denoizzed** [vafour/vafpress-framework#39]
Hello, 

would it be possible to use only let's say Theme Options part from the library? So other in this case unnecessary stuff doesn't load? 

Thanks in advance!

**Comment by ayublin** [comment]
Hi Denoizzed,

Unfortunately that's not currently possible, actually the biggest part of the framework is in it's set of controls, so removing the metabox or shortcode generator codes doesn't reduce that much number of files, but well it's still nice to be efficient :)

But you don't have to worry about the load, because:
1. The framework utilize OOP and Autoloading mechanism, so only instantiated class file will be loaded.
2. We implement a smart scripts and styles loader, so only needed styles and scripts will be enqueued.

Thanks!
