### ISSUE TITLE
Field WP Editor / Add media issue

### ISSUE THREAD

**Issue by OscarWeijman** [vafour/vafpress-framework#69]
WP version 3.9 'add media' not working anymore, for field type 'wpeditor'.
Attachment is not send to the editor.

Tested with the latest version of vafpress / wordpress

**Comment by dameer** [comment]
It looks like nobody gives a care any more. 7 days since Oscar posted the problem regarding "wpeditor" and vafpress team ignores it. Whatta shame!!! If I ever knew vafpress is going to be such a waste-of-support product I'd never use it. Now we are left on our own.

**Comment by ayublin** [comment]
Hi @OscarWeijman we will look into this, I thought fixing the tinymce editor will fix compatibility with 3.9, turns out I can confirm that issue you mentioned. Thanks for reporting.

@dameer we did fix to the WP Editor upon 3.9 release, I gotta admit I missed this one issue. Vafpress is a free and open source, you're a developer your self, there is no reason for you not to lend a hand on this project, will be much better than saying negative things.

**Comment by ayublin** [comment]
Hi again @OscarWeijman, I believe I just pushed out the fix, let me know if it's working or not. Thanks!

**Comment by dameer** [comment]
ayublin, my mate, I'm not an expert, you could be my master teacher when talking about coding. who else but you is capable of resolving VP framework crucial issues? it'll take days for me and maybe a minute for you. however, 7 days without any response regarding WPEditor problem is a shame. many users based their projects on Vafpress and many of them can't lend a hand because they lack the knowledge. you are the captain of the VP ship, you can't just cast off and let passengers sail the seas on their own.

**Comment by ayublin** [comment]
If everyone waits to be an expert before willing to help then no one ever gonna helps, I am no expert myself. There are dozens of open source projects, with a lot of contributors, those people obviously were not the original creators.

You can see I committed a fix related to the WPEditor 8 days ago, so I thought this was fixed which is my fault.

Also there are a lot of different ways to help, just FYI we had a donate button which is not even a single person used. At least be nice when asking: http://www.wpbeginner.com/beginners-guide/how-to-properly-ask-for-wordpress-support-and-get-it/.

**Comment by dameer** [comment]
Man, you are right. I'm not here to fight so take my apologies.

**Comment by ayublin** [comment]
:beers:

**Comment by OscarWeijman** [comment]
It Works! Thanks.
