### ISSUE TITLE
using only one feature 

### ISSUE THREAD

**Issue by agusmu** [vafour/vafpress-framework#8]
Vafpress Framework comes with three great features: Options Page, Metabox Builder, and Shortcode Generator.

Let's say, in one of my plugin I only need shortcode generator and in other plugin I only need options page. 

Is it possible to get "shortcode generator" version only of VafPress Framework?

My concern is file size. I tried to ZIP the plugin/theme boilerparte, and I found the ZIP filesize is still bigger than 800KB. I want to make it simple and smaller. 

Any suggestion from you guys? Or do I need to build my own "light" version of Vafpress Framework to achieve this?

Let me know if Github is not the right place to ask this question.

**Comment by ayublin** [comment]
Hi, the biggest parts of Vafpress Framework are the set of controls, so removing the Metabox, and Shortcode Generator won't give good enough size reduction. We have thought of this matter before, and decided to create a [plugin version](https://github.com/vafour/vafpress-framework-plugin) of Vafpress Framework, so that every plugins using Vafpress Framework can depends their self to Vafpress Framework Plugin, so that they can use the same framework files that live as a plugin, the Vafpress Framework Plugin files will still be big though, but at least it can prevent the duplication of the framework.
